/// Known footwear brands — if the API result is from one of these,
/// we trust it as a shoe without needing keyword heuristics.
const knownFootwearBrands = {
  'nike',
  'jordan',
  'adidas',
  'new balance',
  'asics',
  'converse',
  'vans',
  'puma',
  'reebok',
  'on',
  'hoka',
  'salomon',
  'saucony',
  'under armour',
  'brooks',
  'mizuno',
  'diadora',
  'fila',
  'timberland',
  'dr. martens',
  'ugg',
  'birkenstock',
  'crocs',
  'yeezy',
  'off-white',
  'fear of god',
  'rick owens',
};

/// Retailer / private-label brands that sell mixed categories.
/// These don't exist on StockX/GOAT, so results are always wrong.
const retailerLabels = {
  'goodfellow',
  'cat & jack',
  'cat and jack',
  'universal thread',
  'a new day',
  'all in motion',
  'wild fable',
  'prologue',
  'george',
  'wonder nation',
  'time and tru',
  'athletic works',
  'no boundaries',
  'kirkland',
  'amazon essentials',
  'wrangler',
  'fruit of the loom',
  'hanes',
  'starter',
  'and1',
  'champion c9',
  'avia',
};

/// Footwear-related keywords for products from non-listed brands.
const footwearKeywords = [
  'sneakers',
  'sneaker',
  'shoes',
  'shoe',
  'footwear',
  'boots',
  'boot',
  'sandals',
  'sandal',
  'slides',
  'slide',
  'clogs',
  'clog',
  'mules',
  'mule',
  'slippers',
  'slipper',
  'trainers',
  'trainer',
  'runners',
  'runner',
  'dunk',
  'jordan',
  'yeezy',
  'air max',
  'air force',
  'foam runner',
  'new balance',
  'ultraboost',
  'gel-',
];
